### ISSUE TITLE
Issue with inserting 2nd tileset

### ISSUE THREAD

**Issue by shachar700** [huderlem/porymap#104]
I'm having an issue with the 2nd tileset named gTileset_Petalburg. 
I inserted both tile images of the primary and secondary tilesets and also the primary and secondary metatiles and although it shows me in porymap that it's a working metatile it actually isn't.

In the image you can see both advance map and porymap side by side (after save&compile)
![Screenshot_2](https://user-images.githubusercontent.com/48739719/54651740-e05cdc80-4abc-11e9-8a5d-0b1b7fce981a.png)

P.S btw how do I rename maps?

**Comment by huderlem** [comment]
This is likely because of the makefile rule for that tileset image. In order to match the original ROM, all of the tileset images have very explicit sizes defined in this file: https://github.com/pret/pokeemerald/blob/master/graphics_file_rules.mk

Since you don't care about the explicit size you can safely delete the petalburg line from that file.

**Comment by huderlem** [comment]
Porymap has no way to rename maps. You would need to do that manually.

**Comment by shachar700** [comment]
I safely deleted the petalburg line from that file and still no changes

**Comment by huderlem** [comment]
You might need to "touch" file image file after deleting that line.  (Resave the image to update its last-modified time, so make knows it needs to be updated)

**Comment by shachar700** [comment]
Thanks, it's working. I think you should make an option to be able to insert map from Advance Map.
