### ISSUE TITLE
Porymap support for pokefirered

### ISSUE THREAD

**Issue by ProjectRevoTPP** [huderlem/porymap#180]
https://github.com/pret/pokefirered/issues/217

**Comment by GriffinRichards** [comment]
Porymap needs to be able to handle pokefirered's empty layout initializers (example here: https://github.com/pret/pokefirered/blob/master/data/layouts/layouts.json#L256)

At the moment, version 3.0.0 crashes trying to open pokefirered because it's expecting field names. Previous versions of porymap would open but show a blank layout with no name in the layout view. 

May be reasonable to have porymap throw a warning and skip over the layout. Porymap's old behavior for these layouts could also be restored by explicitly specifying the empty fields on pokefirered's end.

**Comment by ProjectRevoTPP** [comment]
https://github.com/huderlem/porymap/issues/185 is required

**Comment by ProjectRevoTPP** [comment]
Please support blank layouts. (ie, {},) required for pokefirered.

**Comment by GriffinRichards** [comment]
Some other misc changes for pokefirered support:

- Handle `in_connection`. pokefirered uses an object event field that pokeemerald/pokeruby do not for flagging object events that are positioned in a map connection. See https://github.com/pret/pokefirered/pull/260

- pokefirered has different map header property names (see https://github.com/pret/pokefirered/pull/258). These should either be updated in porymap/pokeruby/pokeemerald, or pokefirered should sync to them. Additionally it has one property the others do not ( `floor_number` )

- If it's not handled already, porymap shouldn't read `include/constants/secret_bases.h` for pokefirered because it doesn't exist

**Comment by garakmon** [comment]
Tileset tiles and palettes for General, GenericBuilding1, and DepartmentStore are located in the middle of data/graphics.s and not with the rest of the tileset graphics

**Comment by GriffinRichards** [comment]
Parse the metatile attributes properly.

> Tileset tiles and palettes for General, GenericBuilding1, and DepartmentStore are located in the middle of data/graphics.s and not with the rest of the tileset graphics

Re: the above, palette for General is now successfully located. Tiles/palettes for `GenericBuilding1` and `DepartmentStore` are not because porymap guesses their location based on their, but guesses incorrectly because of the underscore in their name

**Comment by GriffinRichards** [comment]
Heal locations are handled differently in pokefirered, not sure how much of it porymap should handle. In pokeemerald/pokeruby when the player whites out they respawn at a heal location specified by `sHealLocations`. These are also used as spawn points when the player flies to that map. 

In pokefirered when the player whites out they respawn inside the pokemon center (or their house) and are speaking to the nurse (or their mom). The map to respawn in is its own table (`sBlackoutRespawnHealCenterMapIdxs`), and the coordinates to respawn at are set in `SetBlackoutRespawnWarpAndHealerNpc`. The obj id of the NPC the player talks to is set by another table (`sBlackoutRespawnHealerNpcIds`). The fly destinations however are handled the same way as pokeemerald/pokeruby (`sSpawnPoints`). If only the fly destination table is handled, new indices will be out of bounds for the other two tables. 

At the very least the heal location constants should be synced (currently pokefirered uses the name `SPAWN_` and defines them in `include/constants/spawn_points.h`) and the data should be synced (pokefirered needs to move this data from `heal_location.c` to `src/data/heal_locations.h` and sync the name for the fly destination table).

**Comment by GriffinRichards** [comment]
If a pokeemerald/pokeruby project is open with the Region Map Editor open, opening a pokefirered  project will crash porymap. Similarly if the Tileset Editor is open in pokefirered, opening a pokeruby/pokeemerald project will crash porymap. There are probably more "opening another project while a difference is available" issues. I suspect they're related to #184. See comment there for another instance of an issue switching between projects

**Comment by garakmon** [comment]
91f8db10a5ff4a43f99339842aa4315be1c2fd08
