### ISSUE TITLE
porymap does not open anymore

### ISSUE THREAD

**Issue by mertens2** [huderlem/porymap#183]
i used porymap a lot, and its a great tool. but a random day, it randomly stopped working. it doesn't even open anymore, i tried downloading again, but it does nothing. i even tried updating my visual redistributable (i dont remember exactly the name) but it still doesnt open.
it gives me (sometimes) a runtime error, and nothing else
it also used to take a long time to open after all this happen. also, the new warps that i created never worked

**Comment by huderlem** [comment]
Porymap tries to open the recently-opened folder when it starts.  If it can't open it, then it will fail to launch the program, which is what is happening to you.  The reason it can't open your project is because you made some incompatible change to your project's code and porymap doesn't understand it anymore.

1. Look at `%appdata%\pret\porymap\porymap.log` to see what the error is.
2. In `%appdata%\pret\porymap\porymap.cfg`, you can remove the `recent_project` value, so it looks like this: `recent_project=`.  This will make it so you can open porymap again.  However, it will just crash again as soon as you open your broken project.

**Comment by Diegoisawesome** [comment]
Porymap should still die more gracefully than it does now, giving an error and opening anyway without having the project loaded for example

**Comment by huderlem** [comment]
That's what this issue is for: https://github.com/huderlem/porymap/issues/177

**Comment by huderlem** [comment]
This should be fixed with commits: 79c74b8814d640e8550a178cde29e28c024b00f8 ... 2df0ac7d16d71b5145b35988be7e1ff2d2ce39a6
