### ISSUE TITLE
Suggestion: Double-click on connected maps to travel to them from any view, not just the connections view

### ISSUE THREAD

**Issue by Sierraffinity** [huderlem/porymap#245]
Also tangentially tied in, maybe make the border of the current map more distinct (maybe gray out the surrounding maps, or draw a simple rectangle around the map?)

**Comment by huderlem** [comment]
I'm fine with double-clicking a connection in the map or event tabs.

Borders/connections can already be disabled using the checkbox above the map area.  I'd rather not introduce another configurable way of differentiating it from the main map area.  (i.e. As a user, there is a lot of value in the connection being presented how they currently are because it shows exactly what it will look like in-game)

**Comment by BigBahss** [comment]
From @Meister-anon on #369:
> In the map view, clicking the border box, allows us to see the map connections.
> 
> But we still have to go to the connection menu to be able to shift to the next map by clicking on
> the connection.
> 
> Would be a good time-saver and work flow improvement,
> to be able move to the next map, just by clicking on the connection
> from the map view when the border is being shown.
