### ISSUE TITLE
The main window can't be resize for my screen (1024x768)

### ISSUE THREAD

**Issue by Filadelphila** [huderlem/porymap#279]
The main window can not be resize below. Because of this the window can not be maximized.

**Comment by garakmon** [comment]
This appears to be caused by some version compatibility issue in the code that restores the previous window state. 
If you navigate to this file: <https://huderlem.github.io/porymap/manual/settings-and-options.html#porymap-settings> and delete the fields `window_geometry` through `main_splitter_state` in the table, it should resolve itself the next time it opens.

**Comment by BigBahss** [comment]
I'm having the same issue on Manjaro Linux 5.7. I applied the fix mentioned by @garakmon which seemed to allow me to reduce the size of the window width, but not the window height, which is the real problem in my case for my laptop display (1366x768). It's not a problem when connected to my second display (1600x900). Another bit of interesting behavior is that while the window is on my laptop display, the maximize button does nothing, whereas on the second display maximizing works just fine. The window width can only be reduced to a certain point though, and it seems like there's a minimum width and height that appear to be the same since the window looks roughly square. Just thought I'd share.

**Comment by Filadelphila** [comment]
I am on an Arch Linux distribution and I use Gnome 3. I looked on the source code with Qt Designer but I am unable to resolve the issue due to my knowledge of Qt. I guess there is a way to do is. Probably by reducing the minimum size of the window but for some reason I can not do it.

**Comment by garakmon** [comment]
I'm not sure which widget(s) is/are causing this. I have tested the size policies for everything in the Mainwindow form and I can't seem to get the vertical size under than 800 pixels.
