### ISSUE TITLE
Create New Object Bug

### ISSUE THREAD

**Issue by Dragonflysots** [huderlem/porymap#297]
If you create a new Object (maybe a Warp) and you now on this warp and create a new Object (maybe NPCs) they have the attribute of a Warp:

![image](https://user-images.githubusercontent.com/27623565/91844832-70162c80-ec58-11ea-888b-7aa3721181d6.png)

**Comment by BigBahss** [comment]
This bug seems to only occur if the new event you are creating is the first of it's kind on the map, and will show as the last selected event (it is not actually showing new data for this new event, just whatever the last selected event is). This seems to be an issue with porymap not creating the new event type's tab (I confirmed Event::createNewEvent is getting sent the correct event type), and won't show the new event correctly until you until you close and reopen porymap. If you simply reload the project then porymap will crash upon selecting the new event. Just giving info to whoever may tackle this issue, since I don't really know where to go from here.

**Comment by BigBahss** [comment]
@garakmon You probably have a better idea than I do, but I found the offending commit is 1151f9fc26bedaabc85e1a790dcc6dfdea74ccb7 and that MainWindow::updateObjects() just needs to be called when adding a new event.
