### ISSUE TITLE
[Suggestion] Creation of New Groups and New Tilesets

### ISSUE THREAD

**Issue by Gamer2020** [huderlem/porymap#64]
Hi.

I'm sure this is planned for eventually and I apologize if there is already an open item for it. I'd like to suggest the ability to create new/blank groups and new/blank tilesets similar to how a new map can be created.

**Comment by Deokishisu** [comment]
Creating new groups is a simple change in the data/maps/groups.inc file. You can add or remove groups more quickly than any possible porymap UI doing that. Make sure that after you edit the groups.inc file, you open porymap and Save All immediately so that porymap automatically fixes your include/constants/maps.h file to correspond with your new groupings.

**Comment by SBird1337** [comment]
@Deokishisu hmm that sounds not like a very sane process, because you kind of need a tool to fix your `maps.h` but you also kind of don't use a tool and do it manually.

Also: manually editing things like that, especially when normally used with a GUI is always prone to errors.

**Comment by Gamer2020** [comment]
Agree that new groups isn't as bad. 

However, adding new tiles sets seemed tricky to me and I couldn't get it to work manually but I could have been doing something wrong.

**Comment by huderlem** [comment]
Closing, as the remaining work for this Issue is covered by #181
