### ISSUE TITLE
BUG: Tileset images imported after exporting from A-Map are "invalid"

### ISSUE THREAD

**Issue by Diegoisawesome** [huderlem/porymap#72]
When importing a tileset image directly exported from A-Map, the image is said to be invalid according to Porymap though Paint and other programs can read them just fine.

**Comment by huderlem** [comment]
2 things are wrong here:
1. AdvanceMap does not export indexed images.
2. AdvanceMap always saves the file as a .bmp, regardless of which file type you choose to save it as(!!!).

I think porymap could do two things:
1. Better error message for extension not matching the underlying data (I can't find any docs about this quirk in QImage).
2. Prompt for a matching palette file if the image is not indexed.  The user could then select a JASC or a format that AMap can export.  Then, a new indexed QImage would be generated on-the-fly based on the provided palette.

**Comment by huderlem** [comment]
Addressed in fa6166346539ee60537247c26c37e21e6031a9e3 and d58918a554def365a75a4ec6d9d792df0b873759

1. The image data is now read from the filestream, rather than having Qt incorrectly detect the file format based on the file extension.
2. If the uploaded image file is not indexed, it will prompt the user to select a corresponding palette file for it.  Then that palette is used when converting the image to an indexed format.  So the Advance Map use case would be to export both the image and the palette for the tileset your importing.
